# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 00:42
from __future__ import unicode_literals

import apps.register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[apps.register.models.validateNameLength])),
                ('last_name', models.CharField(max_length=50, validators=[apps.register.models.validateNameLength])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, validators=[apps.register.models.validatePasswordLength])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
